// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0D8yao1yhkqT2Hr45WuChCibWvjXpOq0',
    appId: '1:253256338523:web:c52a634d7033da3b43037e',
    messagingSenderId: '253256338523',
    projectId: 'cashmoney-1c7b9',
    authDomain: 'cashmoney-1c7b9.firebaseapp.com',
    storageBucket: 'cashmoney-1c7b9.appspot.com',
    measurementId: 'G-HH75B10255',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX-Dbr3dBBMrDdGzgrNK8CV6jYhtyTYsc',
    appId: '1:253256338523:android:7f7de2877d45c6ba43037e',
    messagingSenderId: '253256338523',
    projectId: 'cashmoney-1c7b9',
    storageBucket: 'cashmoney-1c7b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTPXVTy7wDA8FfdeKA9OlElGvkimCx1Q4',
    appId: '1:253256338523:ios:e6f7cb40cbe2d46743037e',
    messagingSenderId: '253256338523',
    projectId: 'cashmoney-1c7b9',
    storageBucket: 'cashmoney-1c7b9.appspot.com',
    androidClientId: '253256338523-rnle767v2d7j5sd62a7kjr693ikos0ou.apps.googleusercontent.com',
    iosClientId: '253256338523-te8npokrs2nghngr0cn4pml2stfkg3m3.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTPXVTy7wDA8FfdeKA9OlElGvkimCx1Q4',
    appId: '1:253256338523:ios:9c39d9355bb4ea8043037e',
    messagingSenderId: '253256338523',
    projectId: 'cashmoney-1c7b9',
    storageBucket: 'cashmoney-1c7b9.appspot.com',
    androidClientId: '253256338523-rnle767v2d7j5sd62a7kjr693ikos0ou.apps.googleusercontent.com',
    iosClientId: '253256338523-fc25b6t25vifi7s8b1rdsa5lcgjjkib1.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
