

class Qes  {
  final String question ;
  late final bool isChecked ;
  final List<Ans> answers ;

   Qes(this.question ,this.isChecked, this.answers);



}















class Ans  {
  final String answer;

  final bool isCorrect;


   Ans(this.answer, this.isCorrect);




}

List <Qes> questions () {
  List <Qes> list = [];

  list.add(Qes("من هو النبي محمد ﷺ", true,
    [
      Ans('هو محمد بن عبد الله بن عبد المطلب', true),
      Ans('محمد بن عبد الله بن مناف', false),
      Ans('محمد بن عبد الله بن خزامه', false),
      Ans('محمد بن عبد الله بن الشافعي', false),
    ],));
  list.add(Qes("من هو أول من نزل على سطح القمر", true,
    [
      Ans('جو بيدن', false),
      Ans('مدريك فولس', false),
      Ans('نيل أمسترونج', true),
      Ans('مارك زانك', false),
    ],));
  list.add(Qes("كم عدد الأسنان في فم الإنسان العادي", false,
    [
      Ans('40 سنا', false),
      Ans('35 سنا', false),
      Ans('30 سنا', false),
      Ans(' 32 سنا', true),
    ],));
  list.add(Qes("كم عدد أعين الذبابة", false,
    [
      Ans('3 أعين', false),
      Ans(' 5 أعين', true),
      Ans('6 أعين', false),
      Ans('4 أعين', false),
    ],));
  list.add(Qes("كم عدد أرجل العنكبوت", false,
    [
      Ans('6 أرجل', false),
      Ans('4 أرجل', false),
      Ans('8 أرجل', true),
      Ans('10 أرجل', false),
    ],));
  list.add(Qes("اذا يسمى بيت النمل", false,
    [
      Ans('قرية النمل', true),
      Ans('وادي النمل', false),
      Ans('بيت النمل', false),
      Ans('جحر النمل', false),
    ],));
  list.add(Qes("كم عظمة توجد في جسم الإنسان ", false,
    [
      Ans('205 عظمة', false),
      Ans('207 عظمة', false),
      Ans('206 عظمات', true),
      Ans('208 عظمة', false),
    ],));
  list.add(Qes("أين تقع جزيرة لانجرهانز", false,
    [
      Ans('أمريكا الشمالية', false),
      Ans('في اوروبا', false),
      Ans('في الأمعاء', false),
      Ans(' في البنكرياس', true),
    ],));
  list.add(Qes("ماذا يطلق على صوت الماء", false,
    [
      Ans('جرير', false),
      Ans('خرير', true),
      Ans('بئير', false),
      Ans('عليل', false),
    ],));
  list.add(Qes("من الذي اكتشف الصفر", false,
    [
      Ans('الأوروبيين', false),
      Ans('الصينيين', false),
      Ans('االروسيين', false),
      Ans('العرب', true),
    ],));
  list.add(Qes("ماذا يسمى ابن الأسد", false,
    [
      Ans('كهل', false),
      Ans('نمس', false),
      Ans('شبل', true),
      Ans('فحل', false),
    ],));
  list.add(Qes("ما إسم أكبر بحار العالم ", false,
    [
      Ans('البحر الأبيض المتوسط', true),
      Ans('البحر الأحمر', false),
      Ans('البحر الميت', false),
      Ans('البحر الأطلسي', false),
    ],));
  list.add(Qes("ما إسم أطول نهر في العالم", false,
    [
      Ans('نهر الفرات', false),
      Ans('نهر الأمازون', false),
      Ans('نهر النيل', true),
      Ans('نهر ينسي', false),
    ],));
  list.add(Qes("كم عدد الخلفاء الراشدين ", false,
    [
      Ans('3 خلفاء', false),
      Ans('4 خلفاء', true),
      Ans('5 خلفاء', false),
      Ans('6 خلفاء', false),
    ],));
  list.add(Qes("ما هي عاصمة الأرجنتين", false,
    [
      Ans('بونس آيرس', true),
      Ans('بيل ماك', false),
      Ans('لوس أنجلس', false),
      Ans('يتنهام', false),
    ],));
  list.add(Qes("أين يقع مقام سيدنا إبراهيم عليه السلام", false,
    [
      Ans('الرياض', false),
      Ans('الدمام', false),
      Ans('في المدينة المنورة', false),
      Ans('في مكة المكرمة', true),
    ],));
  list.add(Qes("من هم الذين حاولوا هدم الكعبة المشرفة", false,
    [
      Ans('الأحراش', false),
      Ans('الأحباش', true),
      Ans('الأنجاش', false),
      Ans('الأوباش', false),
    ],));
  list.add(Qes(" كم عدد فرائض الوضوء", false,
    [
      Ans('5 فرائض', false),
      Ans('4 فرائض', true),
      Ans('6 فرائض', false),
      Ans('7 فرائض', false),
    ],));
  list.add(Qes("كم عدد الصمامات في قلب الإنسان", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('4 صمامات', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', true),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', true),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  list.add(Qes("lovey", false,
    [
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
      Ans('love you', false),
    ],));
  return list;
}


List <Qes> qes = questions() ;


/*List <Omar> omar = [
  Omar(name1: 'من هو الله عز وجل', name2: 'i love you1', isChecked: false),
  Omar(name1:'من هو سيدنا محمد ﷺ', name2: 'i love you2', isChecked: false),
  Omar(name1: 'ما هو الاسلام', name2: 'i love you4', isChecked: false),
  Omar(name1: 'ما هي أحب الاعمال الي الله', name2: 'i love you5', isChecked: false),
  Omar(name1: 'كم عدد حروف الجر', name2: 'i love you3', isChecked: false),
  Omar(name1: 'من هو أذكي رجل بالعالم', name2: 'وليام جيمس سيديس', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هي أول شهيدة في الاسلام', name2: 'i love you1', isChecked: false),
  Omar(name1:'ما هو أسرع حيوان في العالم', name2: 'i love you2', isChecked: false),
  Omar(name1: 'من هو أفضل لاعب كرة بالعالم', name2: 'i love you3', isChecked: false),
  Omar(name1: 'ماذا تعني الكلمة التالية: أفلاطون', name2: 'الشخص عريض الكتفين', isChecked: false),
  Omar(name1: 'كم يبلغ العدد من الرهط', name2: 'من 10 إلى 30 فرد', isChecked: false),
  Omar(name1: 'ما المقصود بالعُقار', name2: 'الخمر', isChecked: false),
  Omar(name1: 'ماذا تعني كلمة أوروبا', name2: 'أصلها يوناني وتعني الأرض الواسعه', isChecked: false),
  Omar(name1: 'ما معنى كلمة دكتور وما هو أصلها', name2: 'أصلها لاتيني وتعني المعلم والمهندس', isChecked: false),
  Omar(name1: 'من أي اللغات جاءت كلمة البيجاما', name2: 'فارسية وتعني غطاء الأرجل', isChecked: false),
  Omar(name1: 'من هو الشاعر الذي ترجم رباعيات الخيام للغه العربية', name2: 'الشاعر أحمد رامي', isChecked: false),
  Omar(name1: 'ما معنى كلمة الديوان وما هو أصلها', name2: 'أصلها فارسية وتعني الدفتر أو السجل', isChecked: false),
  Omar(name1:'ماذا تعني كلمة فرعون', name2: 'البيت الكبير', isChecked: false),
  Omar(name1: ' متى يمكن أن نطلق على الشعر شعرا', name2: 'اذا كان موزون ويزيد على 10 أبيات', isChecked: false),
  Omar(name1: 'ما معنى أم كلثوم', name2: 'المرأه الممتلئة الجسم', isChecked: false),
  Omar(name1: 'ماذا تعني كلمة العراق', name2: 'شاطئ الماء', isChecked: false),
  Omar(name1: 'ماذا يطلق على مجموعة الخيالة', name2: 'كوكبه', isChecked: false),
  Omar(name1: ' من هو شاعر الفرس الأكبر', name2: 'الفردوسي', isChecked: false),
  Omar(name1: 'من هي الشاعرة صاحبة لقب شاعرة الطبيعة', name2: 'عائشة التيمورية', isChecked: false),
  Omar(name1: ' ما هو أصل كلمة سيراميك', name2: 'فرنسية وتطلق على فن الخزف', isChecked: false),
  Omar(name1: 'ما أصل كلمة بترول', name2: 'لاتينيه وتعني زيت الصخر', isChecked: false),
  Omar(name1: 'من هو أول شهيد في الاسلام', name2: 'الحارث بن أبي هالة التميمي', isChecked: false),
  Omar(name1:'ما هو الدعاء الذي يردده المصلين بين السجدتين', name2: 'اللهم اغفر لي ذنبي', isChecked: false),
  Omar(name1: 'ما هو اسم الملك الذي يقف خازناً على جهنم', name2: 'مالك', isChecked: false),
  Omar(name1: 'متى تنقضي فترة العدة التي أقرها الإسلام للمرأة المطلقة', name2: 'بعد انتهاء ثلاث حيضات', isChecked: false),
  Omar(name1: ' من هو الشخص الذي أُنزلت فيه سورة الهمزة', name2: 'أمية بن خلف', isChecked: false),
  Omar(name1: 'حكم المرأة الناشز في الشرع', name2: 'تأثم وتسقط لها النفقة والسكني', isChecked: false),
  Omar(name1: 'من هم من قيل فيهم بالقرآن الخراصون', name2: 'هم الكذابون', isChecked: false),
  Omar(name1: 'في أي عام تم صلح الحديبية', name2: ' بالعام السادس من الهجرة', isChecked: false),
  Omar(name1: 'ما اسم الدليل الذي كان يقوم بإرشاد الرسول وأبو بكر الصديق أثناء رحلة الهجرة', name2: 'اليهودي (عبد الله بن أريقط)', isChecked: false),
  Omar(name1: 'كان للنبي محمد ﷺ ناقة، ما اسمها', name2: 'القصواء', isChecked: false),
  Omar(name1: 'ماذا كان اسم الدابة التي امتطاها رسول الله في ليلة الاسراء', name2: 'دابة البراق المجنحة', isChecked: false),
  Omar(name1:'من هو أول من صام من الأنبياء', name2: 'سيدنا آدم أبو البشر، فقد كان يصوم ثلاث أيام بالشهر', isChecked: false),
  Omar(name1: 'في أي مسجد استشهد الإمام علي ابن طالب', name2: 'مسجد الكوفة', isChecked: false),
  Omar(name1: 'حكم المرأة المتبرجة', name2: 'تأثم شرعا', isChecked: false),
  Omar(name1: 'في أي غزوة وقعت الشيماء أخت النبي بالرضاعة في الأسر', name2: 'غزوة حنين', isChecked: false),
  Omar(name1: 'من آخر من توفى من زوجات النبي', name2: ' السيدة أم سلمة', isChecked: false),
  Omar(name1: 'من هو أول صحابي تسلم الحجر الأسود', name2: 'الزبير بن العوام', isChecked: false),
  Omar(name1: 'من النبي الذي تمنى الموت', name2: 'النبي يوسف عليه السلام', isChecked: false),
  Omar(name1: 'صحابي ورد اسمه بالقرآن صريحاً', name2: 'زيد بن حارثة', isChecked: false),
  Omar(name1: 'ما اسم أول الصحابة الذي قام بقراءة القرآن جهراً', name2: 'عبد الله بن مسعود', isChecked: false),
  Omar(name1:'أول الأنبياء الذي قام بارتداء السروال', name2: 'إبراهيم عليه السلام', isChecked: false),
  Omar(name1: 'النبي الذي أطلق عليه اسم الذبيح', name2: ' نبي الله اسماعيل', isChecked: false),
  Omar(name1: 'ما هو اسم السورة القرآنية  التي ورد بها سجدتين', name2: 'سورة الحج', isChecked: false),
  Omar(name1: 'أّذكر عدد سجدات التلاوة التي وردت بالقرآن', name2: 'خمسة عشر سجدة', isChecked: false),
  Omar(name1: 'كم عدد أركان الاسلام', name2: 'خمسة', isChecked: false),
  Omar(name1: 'سورة قرآنية يطلق عليها عروس القرآن', name2: 'سورة الرحمن', isChecked: false),
  Omar(name1: 'أول ما تحدث عنه رسول الله حينما قدم إلى المدينة', name2: '(صلوا الأرحام ، وصلوا والناس نيام تدخلوا الجنة بسلام)', isChecked: false),
  Omar(name1: 'ما هي أقصر سورة بالقرآن الكريم', name2: 'سورة الكوثر وعدد آياتها ثلاث آيات', isChecked: false),
  Omar(name1: 'سورة قرآنية لم تبدأ بالبسملة', name2: 'سورة التوبة', isChecked: false),
  Omar(name1: 'ما هي أطول سورة قرآنية', name2: 'سورة البقرة وعدد آياتها مائتان ستة وثمانون آية', isChecked: false),
  Omar(name1:' أول من ألقى تحية الإسلام على الرسول صلى الله عليه وسلم', name2: 'أبو ذر الغِفاري رضى الله عنه', isChecked: false),
  Omar(name1: 'حكم رد السلام', name2: 'فرض عين علي الفرد , فرض كفاية علي الجماعة', isChecked: false),
  Omar(name1: 'حكم تشميت العاطس', name2: 'فرض عين علي الفرد , فرض كفاية علي الجماعة', isChecked: false),
  Omar(name1: 'ما هو المقصود بالرياضة', name2: 'هي تسريع عملية التنفس وتسريع معدل ضربات القلب', isChecked: false),
  Omar(name1: 'متي أقيمت أول بطولة كأس العالم لكرة القدم', name2: 'في عام 1930', isChecked: false),
  Omar(name1: 'هل ينبغي تناول وجبة الافطار', name2: 'نعم , تساهم وجبة الافطار في تحسين الأداء المعرفي , وتقليل الشعور بالتعب والجوع', isChecked: false),
  Omar(name1: 'ما هي الأطعمة الصحية', name2: 'السمك , الخضراوات , الفواكة , المكسرات', isChecked: false),
  Omar(name1: 'كمية الماء التي يحتاجها الجسم يوميا من المياة', name2: 'يحتاج الرجال 3,7 لتر يوميا , والنساء تحتاج 2,7 لتر يوميا', isChecked: false),
  Omar(name1: 'من الذي أخترع الهاتف', name2: ' المخترع الأمريكي ألكسندر غراهام', isChecked: false),
  Omar(name1: 'حكم الرضاع من امرأة نصرانية أو يهودية', name2: 'يجوز الرضاع منهم لأن الرضاع لا يشترط الاسلام', isChecked: false),
  Omar(name1:'ما هي أكبر شركة تخزين بيانات في العالم', name2: 'شركة إي إم سي الأمريكية', isChecked: false),
  Omar(name1: 'ما هي الباقيات الصالحات', name2: 'سبحان الله , والحمد لله , ولا اله الا الله , والله أكبر , ولا حول ولا قوة الا بالله ', isChecked: false),
  Omar(name1: 'لماذا سمي أبو جهل بهذا الاسم', name2: 'لسرعة غضبه', isChecked: false),
  Omar(name1: 'لماذا سمي أبو لهب بهذا الاسم', name2: 'لشدة جماله وشدة أحمرار وجهه', isChecked: false),
  Omar(name1: 'متي يبطل التيمم', name2: 'بوجود الماء', isChecked: false),
  Omar(name1: 'من هو الشخص النرجسي', name2: 'هو الشخص المغرور المتكبر الذي يشعر بالأفضلية عن جميع من حوله', isChecked: false),
  Omar(name1: 'كم عدد ألون قوس قزح', name2: 'سبعة', isChecked: false),
  Omar(name1: 'من هو أول من نزل على سطح القمر', name2: 'نيل أمسترونج', isChecked: false),
  Omar(name1: 'كم عدد الأسنان في فم الإنسان العادي', name2: '32 سنا', isChecked: false),
  Omar(name1: ' كم عدد أعين الذبابة', name2: '5 أعين', isChecked: false),
  Omar(name1:'كم عدد أرجل العنكبوت ', name2: '8 أرجل', isChecked: false),
  Omar(name1: 'ماذا يسمى بيت النمل', name2: 'قرية النمل', isChecked: false),
  Omar(name1: ' كم عظمة توجد في جسم الإنسان', name2: '206 عظمات', isChecked: false),
  Omar(name1: ' أين تقع جزيرة لانجرهانز ', name2: 'في البنكرياس', isChecked: false),
  Omar(name1: 'ماذا يطلق على صوت الماء ', name2: 'خرير', isChecked: false),
  Omar(name1: 'من الذي اكتشف الصفر ', name2: 'العرب', isChecked: false),
  Omar(name1: 'ماذا يسمى ابن الأسد ', name2: 'شبل', isChecked: false),
  Omar(name1: 'ما إسم أكبر بحار العالم', name2: ' البحر الأبيض المتوسط', isChecked: false),
  Omar(name1: 'ما إسم أطول نهر في العالم ', name2: 'نهر النيل', isChecked: false),
  Omar(name1: ' كم عدد الخلفاء الراشدين', name2: '4 خلفاء', isChecked: false),
  Omar(name1:'ما هي عاصمة الأرجنتين ', name2: 'بونس آيرس', isChecked: false),
  Omar(name1: 'أين يقع مقام سيدنا إبراهيم عليه السلام ', name2: 'في مكة المكرمة', isChecked: false),
  Omar(name1: 'من هم الذين حاولوا هدم الكعبة المشرفة ', name2: 'الأحباش', isChecked: false),
  Omar(name1: 'كم عدد فرائض الوضوء ', name2: ' 4 فرائض', isChecked: false),
  Omar(name1: 'كم عدد الصمامات في قلب الإنسان ', name2: '4 صمامات', isChecked: false),
  Omar(name1: 'من هو النبي الملقب بأبي الأنبياء ', name2: 'سيدنا إبراهيم عليه السلام', isChecked: false),
  Omar(name1: 'ما إسم عاصمة هولندا ', name2: 'أمستردام', isChecked: false),
  Omar(name1: ' لماذا لقب سيدنا عثمان بن عفان بذي النورين', name2: 'لأنه تزوج بنتان من بنات الرسول', isChecked: false),
  Omar(name1: 'لماذا لقب سيدنا يونس بصاحب الحوت', name2: ' لأنه لبث أربعين يوما في بطن الحوت', isChecked: false),
  Omar(name1: 'من هو سيف الله المسلول', name2: ' سيدنا خالد بن الوليد', isChecked: false),
  Omar(name1: 'من هي صاحبة الجلالة', name2: 'الصحافة', isChecked: false),
  Omar(name1: ' ماذا يطلق على صوت القلم', name2: 'صرير', isChecked: false),
  Omar(name1:'  ماذا يسمى ابن الكلب  ', name2: 'جرو', isChecked: false),
  Omar(name1: 'ما هو قلب القرءان ', name2: 'سورة يس', isChecked: false),
  Omar(name1: 'ما هي السورة التي لا يوجد بها حرف الفاء', name2: 'سورة الفاتحة', isChecked: false),
  Omar(name1: 'ما إسم السورة التي لا تخلوا من ذكر الله', name2: ' سورة المجادلة', isChecked: false),
  Omar(name1: 'كم عدد سور القرءان الكريم', name2: '114 سورة', isChecked: false),
  Omar(name1: 'لماذا سمي كوكب المريخ بالكوكب الأحمر', name2: ' بسبب لون صخوره الحمر', isChecked: false),
  Omar(name1: 'من هو مكتشف كوكب أورانس', name2: 'وليم هرشن', isChecked: false),
  Omar(name1: ' كم يبلغ قطر الشمس', name2: ' 70.000.000 مليون كم2', isChecked: false),
  Omar(name1: 'ماذا يسمى صوت الحمار', name2: 'نهيق', isChecked: false),
  Omar(name1: 'كم يعادل كوكب المشتري كوكبا من الأرض', name2: '1300 كوكب', isChecked: false),
  Omar(name1:'من هو قائد الملائكة', name2: ' سيدنا جبريل عليه السلام', isChecked: false),
  Omar(name1: 'من هو النبي الوحيد الذي تكلم مع رأي وتكلم مع الله سبحانه وتعالي', name2: 'سيدنا محمد ﷺ ', isChecked: false),
  Omar(name1: ' من هو ملك الأحلام ', name2: 'سيدنا روحائيل عليه السلا', isChecked: false),
  Omar(name1: 'كم سنة عاش سيدنا محمد صلى الله عليه وسلم', name2: '63 سنة', isChecked: false),
  Omar(name1: 'ماذا يسمى صوت الديك', name2: 'صياح', isChecked: false),
  Omar(name1: 'ما إسم والدة السيد المسيح عليه السلام', name2: ' السيدة مريم عليها السلام', isChecked: false),
  Omar(name1: 'ما إسم النبيان اللذان رفعهما الله إلى السماء', name2: 'سيدنا عيسى وإدريس عليهما السلام', isChecked: false),
  Omar(name1: ' ما هي عاصمة روسيا ', name2: 'موسكو', isChecked: false),
  Omar(name1: 'كم يبلغ متوسط دقات قلب الإنسان في الدقيقة', name2: 'حوالي 72 - 80 دقة في الدقيقة', isChecked: false),
  Omar(name1: 'كم يعادل كوكب زحل كوكبا من الأرض', name2: 'حوالي 750 كوكب', isChecked: false),
  Omar(name1: 'ما هو أسم صوت الحصان', name2: 'صهيل', isChecked: false),
  Omar(name1: 'ما هي عملة مصر ', name2: 'الجنيه', isChecked: false),
  Omar(name1:'ما هو أكبر وأضخم حيوان في العالم', name2: ' الحوت الأزرق', isChecked: false),
  Omar(name1: 'كم عدد بنات الرسول صلى الله عليه وسلم', name2: ' 4 بنات', isChecked: false),
  Omar(name1: 'ما هي نوع الموسيقى التي اشتهر بها الزنوج الأمريكيون', name2: 'الجاز', isChecked: false),
  Omar(name1: 'ماذا يسمي صوت الأسد', name2: 'زائير', isChecked: false),
  Omar(name1: 'أين يقع سد مأرب ', name2: 'في اليمن', isChecked: false),
  Omar(name1: 'ما إسم الصحابي الذي أشار للرسول ﷺ بحفر الخندق  ', name2: 'سيدنا سلمان الفارسي', isChecked: false),
  Omar(name1: 'من هو أمير الشعراء', name2: 'أحمد شوقي', isChecked: false),
  Omar(name1: 'ما إسم العنصر الذي يوجد في جميع المركبات العضوية', name2: 'الكربون', isChecked: false),
  Omar(name1: 'ما إسم أول كوكب حطت عليه مركبة (باث فيندر) ', name2: 'كوكب المريخ', isChecked: false),
  Omar(name1: 'ما هي عملة الإمارات', name2: 'الدرهم', isChecked: false),
  Omar(name1:' كم يبلغ طول جسر الملك فهد', name2: ' 25 كم', isChecked: false),
  Omar(name1: 'ماذا يسمي صوت الكلب', name2: 'نباح', isChecked: false),
  Omar(name1: 'ما هو نوع الشجرة الموجودة على العلم اللبناني', name2: 'شجرة الأرز', isChecked: false),
  Omar(name1: ' ما إسم البلد الوحيد الذي ذكر في القرآن الكريم ', name2: 'مصر', isChecked: false),
  Omar(name1: 'ما هي عملة المملكة العربية السعودية', name2: 'الريال', isChecked: false),
  Omar(name1: ' أين يقع المسجد الأموي ', name2: 'في دمشق', isChecked: false),
  Omar(name1: ' كم عدد الخلايا السمعية التي توجد في الأذن ', name2: ' 100 ألف خلية', isChecked: false),
  Omar(name1: ' ما هي سفينة الصحراء ', name2: 'الجمل', isChecked: false),
  Omar(name1: 'ماذا يسمى بيت العصفور', name2: 'عش', isChecked: false),
  Omar(name1: ' ما هي عاصمة المغرب ', name2: 'الرباط', isChecked: false),
  Omar(name1: ' ما هو العضو الذي لم يتمكن الأطباء من زرعه حتي الاّن', name2: 'الدماغ', isChecked: false),
  Omar(name1: 'ما هو الإسم الحقيقي للرئيس الجزائري السابق((هواري بو مدين)) ', name2: 'محمد بو خروبة', isChecked: false),
  Omar(name1:'من هو الرحالة الذي اكتشف أستراليا', name2: 'كوك', isChecked: false),
  Omar(name1: ' ما هي عاصمة اليابان ', name2: 'طوكيو', isChecked: false),
  Omar(name1: 'من هو الرحالة الذي اكتشف نيوزلندا ', name2: ' الهولندي تسمان', isChecked: false),
  Omar(name1: 'ما إسم البلدان اللذان يصل بينهما جسر الملك فهد', name2: 'السعودية والبحرين', isChecked: false),
  Omar(name1: ' ما هي عملة إسبانيا ', name2: 'كم عدد أجنحة النحلة', isChecked: false),
  Omar(name1: ' كم كلية توجد في جسم الإنسان السليم ', name2: 'كليتان', isChecked: false),
  Omar(name1: 'ما إسم المرأة الوحيدة التي ورد ذكرها في القرءان الكريم', name2: ' السيدة مريم عليها السلام', isChecked: false),
  Omar(name1: 'مما تتكون أنياب الفيل', name2: 'من العاج', isChecked: false),
  Omar(name1: 'من هو أول من عبر المحيط الأطلسي بالطائرة ', name2: 'تشارليزند نبرع', isChecked: false),
  Omar(name1: 'من أول من أم المسلمين في صلاتهم', name2: 'مصعب بن عمير', isChecked: false),
  Omar(name1:'ما هو اسم المدينة التي لقبت بمدينة الشمس', name2: 'مدينة بعلبك', isChecked: false),
  Omar(name1: 'ما هي السورة الملقبة بعروس القرءان ', name2: 'سورة الرحمن', isChecked: false),
  Omar(name1: 'من هو القائد الذي قاد المسلمين في معركة عين جالوت', name2: ' سيف الدين قطز', isChecked: false),
  Omar(name1: ' من هو الصحابي الذي تستحي منه الملائكة', name2: 'سيدنا عثمان بن عفان', isChecked: false),
  Omar(name1: 'ما إسم زوجة الرسول التي توفيت بعده وقبل سائر زوجاته', name2: ' السيدة زينب بنت جحش', isChecked: false),
  Omar(name1: 'ما إسم أطول آية في القرءان الكريم ', name2: ' آية الدين في سورة البقرة', isChecked: false),
  Omar(name1: 'في أي عهد من عهود الخلفاء الراشدين كانت حروب الردة', name2: 'في عهد سيدنا أبو بكر الصديق', isChecked: false),
  Omar(name1: 'في أي عهد من عهود الخلفاء الأمويين فتحت الأندلس', name2: ' في عهد الوليد بن المغيرة', isChecked: false),
  Omar(name1: 'ماذا كان إسم البحر الأحمر قديما', name2: 'بحر لوط', isChecked: false),
  Omar(name1: 'من هو الخليفة العباسي الذي كان يحج عاما ويغزو عاما', name2: 'هارون الرشيد', isChecked: false),
  Omar(name1: 'ما إسم الصحابي الذي استضاف الرسول ﷺ بعد الهجرة الي يثرب', name2: ' سيدنا أبو أيوب الأنصاري', isChecked: false),
  Omar(name1: 'ما هو إسم المرأة التي تزوجت 4 من أصحاب  الرسول ﷺ وماتوا شهداء ', name2: 'عائكة بنت زيد', isChecked: false),
  Omar(name1:'من هو الصحابي الذي خرج مع الرسول ﷺ الي الطائف ', name2: 'زيد بن حارثة', isChecked: false),
  Omar(name1: ' في أي بيت من زوجات الرسول توفي هو ', name2: ' في بيت عائشة بنت أبي بكر الصديق', isChecked: false),
  Omar(name1: 'ما إسم آخر غزوة قادها الرسول ﷺ', name2: 'غزوة تبوك', isChecked: false),
  Omar(name1: 'ما هو إسم المدينة المنورة قديما ', name2: 'يثرب', isChecked: false),
  Omar(name1: 'من هو زعيم الغابة', name2: 'الأسد', isChecked: false),
  Omar(name1: 'ما هو إسم المرأة التي حاولت قتل النبي ﷺ بالسم ', name2: 'زينب بنت الحارثة (( يهودية ))', isChecked: false),
  Omar(name1: 'ما إسم أول مولود في الإسلام', name2: 'سيدنا عبد الله بن الزبير', isChecked: false),
  Omar(name1: 'في أي عهد من عهود الخلفاء الراشدين كانت معركة القادسية', name2: ' في عهد سيدنا عمر بن الخطاب', isChecked: false),
  Omar(name1: 'من هو أول من آمن من المدينة المنورة', name2: ' سيدنا أسعد بن زرارة ', isChecked: false),
  Omar(name1: 'ما هي السورة الوحيدة التي تخلو من البسملة ', name2: ' سورة التوبة', isChecked: false),
  Omar(name1:' من هو مؤسس الدولة الأموية', name2: 'معاوية بن أبي سفيان', isChecked: false),
  Omar(name1: ' ما هو الإسم الحقيقي للسيدة زينب بنت جحش', name2: 'برة', isChecked: false),
  Omar(name1: 'من الذي غير إسم السيدة زينب بنت جحش إلى برة', name2: 'الرسول ﷺ', isChecked: false),
  Omar(name1: 'من هي آخر زوجات النبي ﷺ', name2: ' السيدة ميمونة بنت الحارث', isChecked: false),
  Omar(name1: 'ماذا يسمى ذكر السلحفاة', name2: 'الغليم', isChecked: false),
  Omar(name1: 'ما هي السورة التي تكررت فيها البسملة مرتين ', name2: 'سورة النمل', isChecked: false),
  Omar(name1: 'من هي المرأة التي كانت بنت نبي وزوجة نبي', name2: 'هي بنت النبي شعيب وزوجة النبي موسى عليهما السلام', isChecked: false),
  Omar(name1: 'كم كان عمر الرسول ﷺ عندما توفيت أمه', name2: '6 سنوات', isChecked: false),
  Omar(name1: 'في أي سنة تم فتح مكة', name2: ' في السنة الثامنة للهجرة', isChecked: false),
  Omar(name1: 'ما إسم النبي الذي صام ثلاثة أيام حتى رزقه الله ولدا', name2: 'سيدنا زكريا', isChecked: false),
  Omar(name1: 'ما هي المدينة المسماة بقبة الإسلام', name2: 'مدينة البصرة', isChecked: false),
  Omar(name1: 'من هي زوجة الرسول التي جاءها جبريل عليه السلام يقرأها السلام من عند الله', name2: 'السيدة خديجة بنت خويلد', isChecked: false),
  Omar(name1:'من هو أول شهيد في غزوة بدر الكبرى', name2: ' عمير بن الوقاص', isChecked: false),
  Omar(name1: 'كم عدد التكبيرات في صلاة الجنازة', name2: '4تكبيرات', isChecked: false),
  Omar(name1: ' في أي عام وقعت حادثة الإفك ', name2: 'في السنة السادسة للهجرة', isChecked: false),
  Omar(name1: 'ما هي المدينة التي سميت بالبتراء ', name2: 'مدينة سلع', isChecked: false),
  Omar(name1: 'كم سعرة حرارية في الماء ', name2: '', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'لاشيء', isChecked: false),
  Omar(name1: 'أين يوجد دماغ الإنسان', name2: 'في جمجمته', isChecked: false),
  Omar(name1: 'ما الذي يسبب التثاؤب للإنسان', name2: 'النعاس', isChecked: false),
  Omar(name1: 'أين يوجد اللعاب', name2: 'في الفم', isChecked: false),
  Omar(name1: 'في أي قارة توجد دولة السويد ', name2: ' في قارة أوروبا', isChecked: false),
  Omar(name1: ' من أول وزير خارجية للمملكة العربية السعودية ', name2: 'فيصل بن عبد العزيز', isChecked: false),
  Omar(name1: 'في أي سنة ميلادية نزلت الرسالة على سيدنا محمد ﷺ ', name2: 'عام 610 م', isChecked: false),
  Omar(name1:' كم دقيقة في الساعة ', name2: '60 دقيقة', isChecked: false),
  Omar(name1: 'ما هو الشاطئ الذي تقع عليه مدينة بيروت', name2: 'شاطئ البحر المتوسط', isChecked: false),
  Omar(name1: ' من أول وزيرة خارجية تتولى هذا المنصب في العالم', name2: 'باندر****ة', isChecked: false),
  Omar(name1: 'ما هي الشجرة التي ارتبط اسمها بآدم وحواء', name2: 'شجرة التفاح', isChecked: false),
  Omar(name1: 'على من انتصر العرب في معركة عين جالوت', name2: 'على المغول', isChecked: false),
  Omar(name1: ' كم دماغا للدودة', name2: ' 11 دماغا', isChecked: false),
  Omar(name1: 'متى أصبحت ألا سكا ولاية تابعة للأمم المتحدة ', name2: 'عام 1912', isChecked: false),
  Omar(name1: ' ماذا يسمى بيت الأسد', name2: 'عرين', isChecked: false),
  Omar(name1: ' أين يعيش الدب القطبي', name2: ' القطب الشمالي', isChecked: false),
  Omar(name1: 'ما هي صلة القرابة بين الرسول ﷺ وعده اللدود أبو لهب', name2: 'عمه', isChecked: false),
  Omar(name1: 'كم يبلغ عدد الصلوات التي فرضها الله في اليوم والليلة', name2: ' 5 صلوات', isChecked: false),
  Omar(name1: 'ما الشيء الذي لا تراه و لكنه أمامك', name2: 'المستقبل', isChecked: false),
  Omar(name1:'ما هي الدولة التي ألقت القنبلة الذرية على هيروشيما', name2: 'الولايات المتحدة الأمريكية', isChecked: false),
  Omar(name1: ' كم سنة استمرت الحرب بين فرنسا وبريطانيا ', name2: '100 عام', isChecked: false),
  Omar(name1: 'من هي عروس الجنوب', name2: 'سناء محيدلي', isChecked: false),
  Omar(name1: ' مرض ينتج عن قلة الأنسولين في الجسم', name2: 'السكري', isChecked: false),
  Omar(name1: ' ما الدولة العربية التي وصلت لدور 16 من كأس العالم 1934', name2: 'مصر', isChecked: false),
  Omar(name1: ' من هي ملكة سبأ في عهد سيدنا سليمان', name2: 'بلقيس', isChecked: false),
  Omar(name1: 'من الذي وضع علم النحو', name2: ' أبو الأسود الدؤلي', isChecked: false),
  Omar(name1: 'حيوان يعيش في أعماق البحر ولا يتحرك', name2: 'المرجان', isChecked: false),
  Omar(name1: 'ما أقدم عائلة إمبراطورية تحكم منذ660 ق م حتى الآن', name2: 'العائلة اليابانية', isChecked: false),
  Omar(name1: 'مدينة أوروبية تسمى التلال السبعة', name2: 'رومــــــا', isChecked: false),
  Omar(name1: 'كم تبلغ مساحة جبل طارق', name2: '6 كم مربع', isChecked: false),
  Omar(name1: 'من هو زوج فاطمة بنت الخطاب', name2: 'سعيد بن زيد', isChecked: false),
  Omar(name1:'كم تبلغ مساحة الوطن العربي', name2: '14 مليون كم مربع', isChecked: false),
  Omar(name1: 'كم تبلغ مساحة الكرة الأرضية', name2: '510210000 كم مربع', isChecked: false),
  Omar(name1: 'ماذا كانت ديانة الفرس قبيل الإسلام', name2: ' النار ويسمون المجوس', isChecked: false),
  Omar(name1: 'ماذا يسمى صوت الغراب', name2: 'نعيق', isChecked: false),
  Omar(name1: 'أين توجد جزر الكناري', name2: 'إسبانيا', isChecked: false),
  Omar(name1: 'من الذي اخترع الراديو', name2: 'مدام كوري', isChecked: false),
  Omar(name1: 'من هو مخترع الرادار ', name2: 'نايلو ريونج', isChecked: false),
  Omar(name1: ' ما الطائر المسمى الهيثم الأسفح', name2: 'الصقر', isChecked: false),
  Omar(name1: 'متى تأسست جامعة الدول العربية', name2: '1945 م', isChecked: false),
  Omar(name1: 'ما هو أصل الشاعر عمر الخيام ', name2: 'فارسي', isChecked: false),
  Omar(name1: 'ما أكبر الدول العربية إنتاجا للموز', name2: 'الصومال', isChecked: false),
  Omar(name1: ' ما عاصمة الصومال', name2: 'مقديشو', isChecked: false),
  Omar(name1:' من مخترع الهاتف', name2: 'الكسندر غراهام بيل', isChecked: false),
  Omar(name1: 'من هو مخترع التيار الكهربي', name2: 'توماس أديسون', isChecked: false),
  Omar(name1: 'كم دامت خلافة علي بن أبي طالب', name2: '5 سنوات', isChecked: false),
  Omar(name1: 'مدينة عربية تعتبر أكثر المدن ازدحاما بالسكان', name2: 'القاهرة', isChecked: false),
  Omar(name1: 'ما هما الثقلان', name2: 'الإنس والجن', isChecked: false),
  Omar(name1: 'في أي قارة تقع شبه الجزيرة العربية', name2: ' قارة آسيا', isChecked: false),
  Omar(name1: 'ما أطول سورة قرآنية بالآيات', name2: 'البقرة', isChecked: false),
  Omar(name1: ' متى اندلعت الحرب العالمية الثانية', name2: '1939', isChecked: false),
  Omar(name1: ' ما الآية التي أعطيت لقوم ثمود ', name2: 'الناقة', isChecked: false),
  Omar(name1: ' ما هي أكبر بحيرة صناعية في الوطن العربي', name2: 'بحيرة ناصر', isChecked: false),
  Omar(name1: ' من القوم الذين أنزل عليهم المن والسلوى', name2: 'قوم موسى عليه السلام', isChecked: false),
  Omar(name1: 'من القائد الذي قام بثورة ضد الاستعمار الإيطالي في ليبيا', name2: 'عمر المختار', isChecked: false),
  Omar(name1:'من هو النبي الذي رموه إخوته في البئر', name2: 'سيدنا يوسف', isChecked: false),
  Omar(name1: 'من هي أول امرأة مسلمة ماتت في غزوة بحرية', name2: 'أم مسلمة', isChecked: false),
  Omar(name1: 'أين توجد بحيرة كونستانس', name2: 'توجد في ألمانيا', isChecked: false),
  Omar(name1: 'كم مدينة في العالم تحمل اسم الإسكندرية', name2: '44 مدينة', isChecked: false),
  Omar(name1: ' ما اسم أول جراح قام بأول عملية زرع قلب في العالم ', name2: ' كرسيتيان برنار', isChecked: false),
  Omar(name1: 'ما الإسم الحقيقي لسيدنا نوح عليه السلام', name2: 'عبد الغفار', isChecked: false),
  Omar(name1: 'من هو أول رئيس للجمهورية السورية', name2: 'محمد عابد', isChecked: false),
  Omar(name1: 'كم مرة احتلت القدس منذ فجر التاريخ', name2: '24 مرة', isChecked: false),
  Omar(name1: 'من هو الإمبراطور الذي قام ببناء سور الصين العظيم ', name2: 'هوانغ تي', isChecked: false),
  Omar(name1: 'موسيقار ألماني له تسع سيفونات والتاسعة هي الأشهر', name2: 'بيت هوفن', isChecked: false),
  Omar(name1: 'في أي عام أقيم مهرجان الجنادرية للثقافة والتراث لأول مرة ', name2: ' سنة 1985', isChecked: false),
  Omar(name1: 'لماذا سمي سيدنا نوح بهذا الإسم', name2: 'لكثرة نواحه وبكائه', isChecked: false),
  Omar(name1:'في أي سنة تم صلح الحديبية', name2: 'في السنة السادسة للهجرة', isChecked: false),
  Omar(name1: 'في أي سنة هجرية توفي ﷺ', name2: 'في السنة11 للهجرة', isChecked: false),
  Omar(name1: 'ما هو أصل أوكسترا', name2: ' يوناني', isChecked: false),
  Omar(name1: 'كم عدد الأولاد الذكور للملك عبد العزيز', name2: ' 36 ذكر', isChecked: false),
  Omar(name1: ' حيوان ليس له جهاز صوتي', name2: 'الزرافة', isChecked: false),
  Omar(name1: ' دولة يمر فيها نهر الفرات قبل العراق', name2: 'سوريا', isChecked: false),
  Omar(name1: 'من هو مؤسس الدولة الأموية في الأندلس', name2: 'عبد الرحمن الداخل', isChecked: false),
  Omar(name1: 'كم عدد الجمهوريات في الاتحاد السوفيتي قبل انهياره', name2: '15 جمهورية', isChecked: false),
  Omar(name1: 'ما عاصمة ليبيا ', name2: 'طرابلس', isChecked: false),
  Omar(name1: 'بما أهلك الله قوم نوح عليه السلام ', name2: 'الطوفان', isChecked: false),
  Omar(name1: 'ما الدولة الأوروبية التي استعمرت إندونيسيا', name2: 'هولندا', isChecked: false),
  Omar(name1: 'ما عاصمة بريطانيا', name2: 'لندن', isChecked: false),
  Omar(name1:'ما هي الدولة التي انفصلت عنها بنغلادش عام1971', name2: 'باكستان', isChecked: false),
  Omar(name1: 'من البطل الذي استشهد بمعركة ميسلون', name2: 'يوسف العظمة', isChecked: false),
  Omar(name1: ' ما عاصمة جزيرة هوكايدا اليابانية ', name2: 'سابورو', isChecked: false),
  Omar(name1: ' من هو مؤلف كتاب التهافت التهافت', name2: 'ابن رشد', isChecked: false),
  Omar(name1: 'ما عاصمة مدغشقر', name2: ' انتاناناريفو', isChecked: false),
  Omar(name1: 'ما اسم زي الرجال في السنغال ', name2: 'البوبو', isChecked: false),
  Omar(name1: ' كم خلية في جسم الإنسان', name2: ' ملايين الخلايا', isChecked: false),
  Omar(name1: 'في أي مدينة ولد السيد المسيح', name2: ' في بيت لحم', isChecked: false),
  Omar(name1: 'ما أشهر جوائز العالم', name2: 'جوائز نوبل', isChecked: false),
  Omar(name1: ' كم عدد الدول التي لها حق الفيتو في العالم', name2: ' 5 دول', isChecked: false),
  Omar(name1: 'ما عاصمة الشيشان', name2: 'غروزني', isChecked: false),
  Omar(name1: 'متى اغتيل المهاتما غاندي', name2: '1948', isChecked: false),
  Omar(name1:' من الديانات المهمة في اليابان ومعناها الطريق إلى الآلهة', name2: 'الشنتو', isChecked: false),
  Omar(name1: 'كم حرب عالمية حدثت حتى الآن', name2: 'حربان', isChecked: false),
  Omar(name1: 'ما عاصمة جزر القمر', name2: 'موروني', isChecked: false),
  Omar(name1: 'من أين نحصل على طبق الكاري', name2: 'من الهند', isChecked: false),
  Omar(name1: 'حيوان يستخرج منه العنبر', name2: 'الحوت', isChecked: false),
  Omar(name1: 'في أي بلد نشأت رياضة الجودو ', name2: 'الصـيـن', isChecked: false),
  Omar(name1: 'آية قرآنية توجد بها جميع الحروف الأبجدية', name2: 'آخر آية من سورة الفتح', isChecked: false),
  Omar(name1: 'سورة سميت بسورة القتال', name2: 'سورة محمد ﷺ', isChecked: false),
  Omar(name1: 'سورة سميت بسورة التنزيل', name2: 'سورة الزمر', isChecked: false),
  Omar(name1: 'سورة سميت بسورة الصدّيق', name2: 'سورة يوسف عليه السلام', isChecked: false),
  Omar(name1: ' كم يستغرق وصول ضوء الشمس إلى الأرض', name2: 'ثمان دقائق وثلاث ثوان', isChecked: false),
  Omar(name1: 'من الذي أطلق على مصر أنها أرض الكنانة', name2: 'عمرو بن العاص', isChecked: false),
  Omar(name1: 'ما اسم أول دولة عربية عرفت الصحافة', name2: 'مصر', isChecked: false),
  Omar(name1: 'من أول من وضع علم الجبر ', name2: 'جابر بن حيان', isChecked: false),
  Omar(name1: 'من هي التي لقبت بالخنساء', name2: 'تماضر بنت عمرو بنت الرشيد', isChecked: false),
  Omar(name1: 'في أي سنة أقيمت أول بطولة لكرة القدم في العالم', name2: 'عام 1930', isChecked: false),
  Omar(name1: ' كم عدد أجزاء القرآن الكريم', name2: '30 جزء', isChecked: false),
  Omar(name1: 'من الذي ابتكر اسم الأمم المتحدة', name2: 'روزفلت', isChecked: false),
  Omar(name1: 'من أول من رسم أول خريطة في العالم', name2: 'الإدريسي', isChecked: false),
  Omar(name1: 'ما أكبر دولة لإنتاج النفط في العالم', name2: 'السعودية', isChecked: false),
  Omar(name1: 'كم عدد الدول العربية في العالم', name2: '22 دولة', isChecked: false),
  Omar(name1: 'ما الدولة الأوروبية التي استعمرت إرتريا وليبيا والصومال', name2: 'إيطاليا', isChecked: false),
  Omar(name1: 'من الذي كان أول حاكم للأندلس', name2: 'موسى بن نصير', isChecked: false),
  Omar(name1: 'متى وقع زلزال الأصنام شمال غرب الجزائر', name2: 'عام 1980', isChecked: false),
  Omar(name1: 'ما هي عاصمة الإمارات', name2: ' أبو ظبي', isChecked: false),
  Omar(name1: 'ما الدولة التي استعمرت لبنان وسوريا والجزائر', name2: 'فرنسا', isChecked: false),
  Omar(name1: 'ما عاصمة البحرين', name2: 'المنامة', isChecked: false),
  Omar(name1: 'من الذي أسس جامع الأزهر في القاهرة', name2: 'جوهر الصقلي', isChecked: false),
  Omar(name1: 'ما معنى كلمة ريال باللغة الإسبانية', name2: 'ملكي', isChecked: false),
  Omar(name1: 'في أي مدينة يوجد المسجد النبوي الشريف', name2: 'في المدينة المنورة', isChecked: false),
  Omar(name1: 'من الذي رسم لوحة الموناليزا', name2: 'ليوناردو دافنشي', isChecked: false),
  Omar(name1: 'من النبي الذي لم يكن له أب فقط', name2: 'سيدنا عيسى عليه وسلم', isChecked: false),
  Omar(name1: 'من النبي الذي عرف منذ صغره بالجمال', name2: 'سيدنا يوسف عليه السلام', isChecked: false),
  Omar(name1: 'ما الإسم الحقيقي لنبي الله إسرائيل عليه السلام', name2: 'سيدنا يعقوب عليه السلام', isChecked: false),
  Omar(name1: 'كم سنة يساوي العقد', name2: ' 10 سنوات', isChecked: false),
  Omar(name1: 'ما الدولة التي استعمرت الهند ومصر والسودان', name2: 'بريطانيا', isChecked: false),
  Omar(name1: 'من الرئيس الأمريكي الذي أرغم على تقديم استقالته قبل انتهاء ولايته ', name2: 'نيكسون', isChecked: false),
  Omar(name1: 'في أي عام تم تتويج الملكة إليزابيت ملكة على المملكة المتحدة', name2: 'عام 1953', isChecked: false),
  Omar(name1: 'ماذا يسمى صوت الجرس', name2: 'رنين', isChecked: false),
  Omar(name1: 'ما الذي يعتمد عليه التقويم الهجري', name2: 'القمر', isChecked: false),
  Omar(name1: 'ما الجزء الذي يسمى المح من البيضة', name2: 'الصفار', isChecked: false),
  Omar(name1: 'ما اسم الممر الذي يصل البحر الأبيض بالمتوسط', name2: 'قناة السويس', isChecked: false),
  Omar(name1: 'كم عدد الصحابة المبشرون بالجنة', name2: '10 أصحاب', isChecked: false),
  Omar(name1: ' متى استقلت الكويت', name2: 'عام 1961', isChecked: false),
  Omar(name1: 'دولتان يقع بينهما مضيق جبل طارق', name2: 'المغرب وإسبانيا', isChecked: false),
  Omar(name1: ' ما اسم أكبر خليج في العالم', name2: 'خليج المكسيك', isChecked: false),
  Omar(name1: 'دولة عربية حكمها جعفر النميري', name2: 'السودان', isChecked: false),
  Omar(name1: 'شهر هجري أنزل فيه القرآن', name2: ' شهر رمضان', isChecked: false),
  Omar(name1: ' ما الإسم الذي تعرف به مدينة إسطنبول', name2: 'القسطنطينية', isChecked: false),
  Omar(name1: 'متى وقع زلزال أغادير في المغرب', name2: 'عام 1960', isChecked: false),
  Omar(name1: 'ما هي عملة فرنسا ', name2: 'الفرنك', isChecked: false),
  Omar(name1: ' أين تقع مدينة سوسة', name2: 'تقع في ليبيا وفي تونس', isChecked: false),
  Omar(name1: 'ما الإسم الذي اشتهر به جنود الجيش الثامن البريطاني خلا ل الحرب العالمية الثانية', name2: ' فئران الصحراء', isChecked: false),
  Omar(name1: 'قارة تعرف بالقارة السمراء', name2: 'أفريقيا', isChecked: false),
  Omar(name1: 'كم يستغرق زمن مباراة كرة القدم', name2: 'ساعة ونصف', isChecked: false),
  Omar(name1: ' ما السباق المعروف بالرالي', name2: 'سباق السيارات', isChecked: false),
  Omar(name1: 'ما عاصمة فنلندا', name2: 'هلسنكي', isChecked: false),
  Omar(name1: 'ما عاصمة ولاية تكساس الأمريكية', name2: 'أوستن', isChecked: false),
  Omar(name1: 'ما اسم ذكر الأرنب', name2: 'الخزر', isChecked: false),
  Omar(name1: 'من الذي قتل سيدنا عمر بن الخطاب', name2: ' أبو لؤلؤة المجوسي', isChecked: false),
  Omar(name1: ' في أي مدينة أمريكية وقع ميثاق الأمم المتحدة ', name2: 'تالاهاسي', isChecked: false),
  Omar(name1: 'من النبي الذي دعا ربه قائلا رب نجني وأهلي مما يعملون', name2: 'سيدنا لوط عليه السلام', isChecked: false),
  Omar(name1: 'كم عدد الفقرات في رقبة الزرافة', name2: ' سبع فقرات', isChecked: false),
  Omar(name1: 'ما اسم أول مؤذن في الإسلام', name2: 'بلال بن رباح', isChecked: false),
  Omar(name1: ' من أي صنف التي تنتمي إليه السلاحف', name2: 'الزواحف', isChecked: false),
  Omar(name1: ' أين حطت المركبة الفضائية الأمريكية أبولو 11 في عام 1969', name2: 'سطح القمر', isChecked: false),
  Omar(name1: 'ماذا تعني الحروف (d N A) بالعربي', name2: 'الحمض النووي منزوع الأكسجين', isChecked: false),
  Omar(name1: ' في أي مدينة يقع المسجد الإبراهيمي الشريف', name2: 'في مدينة الخليل بفلسطين', isChecked: false),
  Omar(name1: ' من الذي وضع نظام الهندسة المسطحة', name2: 'إقليدس', isChecked: false),
  Omar(name1: 'من هو الخليفة العباسي الثامن الذي تزوج 8 مرات وله 8 أولاد وحكم 8 سنوات', name2: 'المعتصم بالله', isChecked: false),
  Omar(name1: 'ما الإسم الحقيقي لبيليه نجم الكرة البرازيلي', name2: 'أديسون أريتس', isChecked: false),
  Omar(name1: 'من الذي اكتشف نهر الأمازون ', name2: ' أمريغو فيسبوتشي', isChecked: false),
  Omar(name1: 'متى اكتشف نهر الأمازون', name2: 'عام 1499', isChecked: false),
  Omar(name1: 'إحدى بنات الرسول صلى الله عليه وسلم وتلقب بالزهراء', name2: ' السيدة فاطمة', isChecked: false),
  Omar(name1: 'ما درجة غليان الماء بالفهرنهايت', name2: '212 درجة', isChecked: false),
  Omar(name1: 'ما درجة تجمد الماء بالفهرنهايت', name2: '32 درجة', isChecked: false),
  Omar(name1: 'كم ملكة لخلية النحل الواحدة ', name2: 'ملكة واحدة فقط', isChecked: false),
  Omar(name1: 'عيم عربي مغربي ثار ضد الأسبان عام 1919', name2: 'عبد الكريم الخطابي', isChecked: false),
  Omar(name1: 'ولاية أمريكية عاصمتها أولومبيا ', name2: 'واشنطن', isChecked: false),
  Omar(name1: 'قرص شفاف يشكل الجزء الخارجي للعين', name2: 'القرنية', isChecked: false),
  Omar(name1: 'ما عاصمة قرغيزستان', name2: 'بشكيك', isChecked: false),
  Omar(name1: 'أين أسست الدولة الفاطمية', name2: 'تونس', isChecked: false),
  Omar(name1: 'كم زوجة تزوج الملك البريطاني هنري الثامن', name2: '6 زوجات', isChecked: false),
  Omar(name1: 'ما عاصمة منغوليا ', name2: 'أولا باتور', isChecked: false),
  Omar(name1: 'كم عدد الدول العربية التي عملتها الريال في شبه الجزيرة العربية', name2: '4 دول', isChecked: false),
  Omar(name1: 'ما الولاية الأمريكية التي عاصمتها فرانكفورت', name2: 'كنتاكي', isChecked: false),
  Omar(name1: 'مدينة سورية ومنطقة في الكويت لهما نفس الإسم', name2: 'تدمر', isChecked: false),
  Omar(name1: 'من هو مخرج ثلاثية الكاتب نجيب محفوظ', name2: 'حسن الإمام', isChecked: false),
  Omar(name1: 'كم دولة عربية عملتها الدينار في أفريقيا', name2: '4 دول', isChecked: false),
  Omar(name1: 'من الخليفة العباسي الذي لقب بالمقتدر بالله', name2: 'جعفر بن أحمد', isChecked: false),
  Omar(name1: 'ما أصل كلمة فساتين', name2: 'فارسي', isChecked: false),
  Omar(name1: 'من الذي تولى رئاسة سوريا بعد جمال عبد الناصر ', name2: 'ناظم القدسي', isChecked: false),
  Omar(name1: 'كم مرة وردت (فبأي آلاء ربكما تكذبان ) في سورة الرحمن ', name2: '31 مرة', isChecked: false),
  Omar(name1: 'ما عاصمة إيطاليا ', name2: 'روما', isChecked: false),
  Omar(name1: 'ماذا يسمى صغير الفرس', name2: 'مهر', isChecked: false),
  Omar(name1: 'ما الدولة المنتجة لسيارات الفولفو ', name2: 'السويد', isChecked: false),
  Omar(name1: 'من الفرعون الذي قام ببناء تمثال أبو الهول في مصر', name2: 'الفرعون خفرع', isChecked: false),
  Omar(name1: 'ما عاصمة العراق', name2: 'بغداد', isChecked: false),
  Omar(name1: 'كم ضلعا لشبه المنحرف', name2: '4 أضلاع', isChecked: false),
  Omar(name1: 'ماذا تسمى أنثى الحمار', name2: 'الأتان', isChecked: false),
  Omar(name1: 'متى كانت أول حملة صليبية على القدس', name2: 'عام 1099 م', isChecked: false),
  Omar(name1: 'ما عاصمة سلطنة عمان', name2: 'مسقط', isChecked: false),
  Omar(name1: 'كم دولة عربية يمر فيها نهر الفرات', name2: 'دولتان', isChecked: false),
  Omar(name1: 'في أي يوم يتشاجر النمل الأبيض مع النمل الأسود ويتشاجر النمل الأخضر مع البني للحصول على رحيق الزهر الأحمر والأبيض ', name2: 'يوم 3 ربيع الأول', isChecked: false),
  Omar(name1: 'كم عدد أيام السنة على كوكب عطارد ', name2: '88 يوم', isChecked: false),
  Omar(name1: 'من الذي اخترع السماعة التي تستعمل في الطب', name2: 'رينيه لاينيك', isChecked: false),
  Omar(name1: 'من الذي ابتكر شخصية طرزان ', name2: 'ادغار بوروز', isChecked: false),
  Omar(name1: 'ما العملة الرئيسية لسوريا', name2: 'الليرة', isChecked: false),
  Omar(name1: 'كم عدد الدول العربية التي لها نفس اسم عاصمتها', name2: '4 دول', isChecked: false),
  Omar(name1: 'من الخليفة الراشدي الذي مات ولم يقتل', name2: 'أبو بكر الصديق', isChecked: false),
  Omar(name1: 'من أول رئيس لإندونيسيا بعد أن نالت استقلالها', name2: 'سو كارنو', isChecked: false),
  Omar(name1: 'ما اللون الذي ينتج عن تجمع ألوان الطيف السبعة', name2: 'اللون الأبيض', isChecked: false),
  Omar(name1: 'كم دولة يمر فيها نهر النيل', name2: '9 دول', isChecked: false),
  Omar(name1: 'من هي أول شهيدة في الإسلام ', name2: 'سمية امرأة سيدنا ياسر', isChecked: false),
  Omar(name1: 'ما الإسم الحقيقي للرئيس الراحل ياسر عرفات', name2: 'محمد رؤوف القدوة', isChecked: false),
  Omar(name1: 'ما الدولة الأولى في إنتاج الفضة', name2: 'المكسيك', isChecked: false),
  Omar(name1: 'ما أغلى أنواع التوابل ثمنا', name2: 'الزعفران', isChecked: false),
  Omar(name1: 'أي الدول العربية التي يجري بها نهر أم الربيع ', name2: 'المغرب', isChecked: false),
  Omar(name1: 'كم عدد الدول العربية التي عملتها الدينار', name2: '8 دول', isChecked: false),
  Omar(name1: 'كم عدد الكويكبات ما بين المريخ والمشتري', name2: 'حوالي 1500 كويكب', isChecked: false),
  Omar(name1: 'كم نسبة الماء على سطح الأرض نسبة لليابس', name2: '71%', isChecked: false),
  Omar(name1: 'كم نسبة اليابس على سطح الأرض نسبة للماء', name2: '29%', isChecked: false),
  Omar(name1: 'ما أطول الحروب في العالم', name2: 'حرب فرنسا وبريطانيا استمرت 100 عام', isChecked: false),
  Omar(name1: 'الحوت .هل يبيض أم يلد', name2: 'يلد', isChecked: false),
  Omar(name1: 'ماذا يسمى صوت الماء', name2: 'خرير', isChecked: false),
  Omar(name1: 'كم عدد كلمات سورة الفاتحة وكم عدد حروفها', name2: '19كلمة/ 124 حرف (على رواية قالون عن نافع )', isChecked: false),
  Omar(name1: 'ما المعجزة الكبرى لمحمد بن عبد الله ﷺ', name2: 'القرآن الكريم', isChecked: false),
  Omar(name1: 'أيهما أطول السنة الشمسية أم القمرية', name2: 'السنة الشمسية', isChecked: false),
  Omar(name1: 'بيت النمل اسمه:قرية- خلية- وكر', name2: 'قرية', isChecked: false),
  Omar(name1: 'ما أشهر قبيلتين في المدينة المنورة', name2: 'الأوس والخزرج', isChecked: false),
  Omar(name1: 'ما أول الناس إسلاماً من الرجال- النساء-الأطفال', name2: 'من الرجال أبو بكر الصديق-من النساء خديجة بنت خويلد- من الأطفال على بن أبى طالب', isChecked: false),
  Omar(name1: ' ما إسم صغير الطير', name2: 'كتكوت', isChecked: false),
  Omar(name1: 'ما أكبر مدينة في الوطن العربى سكانا', name2: 'القاهرة', isChecked: false),
  Omar(name1: ' ماذا تسمى الفتحة الموجودة أعلى المعدة', name2: 'الفؤاد', isChecked: false),
  Omar(name1: 'ماذا يسمى صوت الثعبان', name2: 'فحيح', isChecked: false),
  Omar(name1: 'آي سورة في القرآن الكريم لا يوجد فيها حرف الميم', name2: 'سورة الكوثر', isChecked: false),
  Omar(name1: 'من نام في فراش النبي ليلة الهجرة', name2: 'علي بن أبى طالب', isChecked: false),
  Omar(name1: 'ما القارة التي تضم نصف سكان العالم', name2: 'قارة آسيا', isChecked: false),
  Omar(name1: 'آيهما اكثر ليونة الذهب آم الفضة', name2: 'الذهب', isChecked: false),
  Omar(name1: 'ما اصلب أنواع الحجارة', name2: 'الجرافيت', isChecked: false),
  Omar(name1: 'من سيد الشهداء في أحد', name2: 'حمزة بن عبد المطلب', isChecked: false),
  Omar(name1: 'من اصغر من قاد جيشاً إسلامياً', name2: 'أسامة بن زيد', isChecked: false),
  Omar(name1: 'كم بسملة(بسم الله الرحمان الرحيم) في القرآن الكريم', name2: '114 بسملة', isChecked: false),
  Omar(name1: 'ما هي السورة التي تعادل قراءتها ثلث القرآن', name2: 'سورة الإخلاص', isChecked: false),
  Omar(name1: ' من صاحب سر رسول الله صلى الله عليه وسلم في المنافقين', name2: 'حذيفة بن اليمان', isChecked: false),
  Omar(name1: 'كل الإمارات العربية المتحدة على الخليج العربى إلا واحدة فما هي', name2: 'أم القبوين', isChecked: false),
  Omar(name1: 'ما المعجزة التي جاء بها النبي الصالح إلى قومه وهل صدقوه', name2: 'معجزة الناقة-بعضهم صدقوه والكثير كذبوه', isChecked: false),
  Omar(name1: ' ما عدد المصاحف التي كتبت في عهد عثمان بن عفان', name2: '14 مصحف تقريباً', isChecked: false),
  Omar(name1: 'كم كان سن الرسول حين بعث', name2: '40 سنة', isChecked: false),
  Omar(name1: 'هل في القرآن آية تتألف من كلمة واحدة وفي أي سورة', name2: 'مدهامتآن-سورة الرحمن', isChecked: false),
  Omar(name1: 'ما الأبيضان وما الأصفران', name2: 'الأبيضان هما السكر والملح-الأصفران هما الذهب و النحاس', isChecked: false),
  Omar(name1: 'ما عدد أجنحة البرغوث', name2: 'لا يوجد أجنحة بل يمشي قفزاً', isChecked: false),
  Omar(name1: 'ما الاسم القديم للمحيط الأطلسى', name2: 'بحر الظلمات', isChecked: false),
  Omar(name1: 'ما أطول خلايا الجسم عمراً', name2: 'الدماغ', isChecked: false),
  Omar(name1: 'ما الذهب الأبيض الذهب الأسود الذهب الصفر', name2: 'الذهب الأبيض: القطن/الذهب الأسود: البترول/ الذهب الصفر: الذهب', isChecked: false),
  Omar(name1: 'ما مسافة السفر المبيحة للفطر في رمضان', name2: '82 كم', isChecked: false),
  Omar(name1: 'أين يقع قبر صلاح الدين الأيوبى', name2: 'دمشق', isChecked: false),
  Omar(name1: 'أيهما أسرع انتشارا الصوت أم الضوء', name2: 'الضوء', isChecked: false),
  Omar(name1: 'ما اسم النهر الذى يربط سورية بلبنان', name2: 'نهر العاصى', isChecked: false),
  Omar(name1: 'ماذا يسمى صوت البوم؟وصوت الغراب', name2: 'صوت البوم: نعيق/صوت الغراب:نعيق', isChecked: false),
  Omar(name1: 'أيهما أشد خطرا لمنافق؟أم الكافر', name2: 'المنافق أشد خطراً', isChecked: false),
  Omar(name1: ' كم أقام النبى بمكة بعد البعثة؟وكم أقام بالمدينة', name2: 'أقام بمكة 12 عاماً و أقام بالمدينة 11 عاماً', isChecked: false),
  Omar(name1: 'من أم النبى إسماعيل عليه السلام', name2: 'هاجر عليها السلام', isChecked: false),
  Omar(name1: 'امرأتان ضرب الله بهما مثلاً للذين آمنوا. من هما', name2: 'امرأة فرعون- السيدة مريم عليها السلام', isChecked: false),
  Omar(name1: ' لماذا سميت عاصمة ليبيا طرابلس الغرب', name2: 'لقربها من طرابلس الشام', isChecked: false),
  Omar(name1: 'من هو اكثر الناس إيذاء للرسول(ص)', name2: 'عقبة بن معيط-أبو لهب-أبو جهل-عبد الله بن أُبي', isChecked: false),
  Omar(name1: 'نبي تكلم وهو في المهد', name2: 'سيدنا عيسى عليه السلام', isChecked: false),
  Omar(name1: 'من هو قائد معركة عين جالوت', name2: 'سيف الدين قطز', isChecked: false),
  Omar(name1: 'ما أكبر البحيرات في قارة أفريقيا', name2: 'فيكتوريا', isChecked: false),
  Omar(name1: 'ما هي أقوى عضلة في جسم الإنسان', name2: 'القلب وتعمل بمتوسط عمر الإنسان 70 سنة تقريبا', isChecked: false),
  Omar(name1: 'ما هو أذكى حيوان في العالم ', name2: 'الدلفين', isChecked: false),
  Omar(name1: 'من التي لقبت على زمن رسول الله بآكلة الأكباد', name2: 'هند بنت عتبة', isChecked: false),
  Omar(name1: 'لماذا لا يعيش السمك في البحر الميت', name2: 'لأنه شديد الملوحة', isChecked: false),
  Omar(name1: 'ما أقرب الكواكب إلى الشمس', name2: 'عطارد', isChecked: false),
  Omar(name1: 'ما أبعد الكواكب عن الشمس', name2: 'بلوتو', isChecked: false),
  Omar(name1: 'إلى أي جهة يشير النجم القطبي ', name2: 'إلى الشمال', isChecked: false),
  Omar(name1: 'كم عدد خطوط الطول', name2: '360 خط', isChecked: false),
  Omar(name1: 'كم عدد دوائر العرض', name2: '180 دائرة', isChecked: false),
  Omar(name1: 'كم قمرا تابعا للأرض', name2: 'قمر واحد', isChecked: false),
  Omar(name1: 'من أول من نزل على سطح الأرض من البشر ', name2: 'سيدنا آدم وحواء', isChecked: false),
  Omar(name1: 'ما عاصمة ولاية ألاسكا ', name2: 'جونو', isChecked: false),
  Omar(name1: 'دولة كان اسمها العفار والعيسى', name2: 'جيبوتي', isChecked: false),
  Omar(name1: 'ما العاصمة العربية التي فتحها بطليموس الثاني وسماها فيلادلفيا', name2: 'عمان', isChecked: false),
  Omar(name1: 'صحابية سميتبذات النطاقين', name2: 'أسماء بنت أبي بكر', isChecked: false),
  Omar(name1: 'من أول رئيس أمريكي صار ابنه رئيس للولايات المتحدة', name2: 'جون آدمز', isChecked: false),
  Omar(name1: 'ما هو العسجد', name2: 'الذهب', isChecked: false),
  Omar(name1: 'ما المادة الرئيسة التي يحتويها معجون الأسنان', name2: 'الفلوريد', isChecked: false),
  Omar(name1: 'من هو الذي كان يؤذي الرسول صلى الله عليه وسلم فذمه الله في القرآن ', name2: 'أبو لهب', isChecked: false),
  Omar(name1: 'ما العاصمة العربية التي سميت بالمثلثة ', name2: 'الخرطوم', isChecked: false),
  Omar(name1: 'ما العاصمة العربية التي أطلق عليها اسم جلق', name2: 'دمشق', isChecked: false),
  Omar(name1: 'بما يبحث علم الأثيولوجيا ', name2: 'في سلوك الحيوانات', isChecked: false),
  Omar(name1: 'أين ولد كريستوف كولومبس', name2: 'ولد في إيطاليا', isChecked: false),
  Omar(name1: 'ما اللون الذي ترتاح له العين', name2: 'الأخضر', isChecked: false),
  Omar(name1: 'بكم تكون قوة جاذبية الشمس أقوى من جاذبية الأرض', name2: '28 مرة', isChecked: false),
  Omar(name1: 'ما أصل كلمة أستاذ', name2: 'فارسي', isChecked: false),
  Omar(name1: 'من هو العالم المسلم الملقب بحجة الإسلام', name2: 'الغزالي', isChecked: false),
  Omar(name1: 'ما الذي اخترعه ألفريد نوبل عام 1867', name2: 'الديناميت', isChecked: false),
  Omar(name1: 'ما عاصمة بوركينا فاسو', name2: 'واغادوغو', isChecked: false),
  Omar(name1: 'ما هو الشهد', name2: 'العسل', isChecked: false),
  Omar(name1: 'في أي مدينة توفي الشاعر نزار القباني', name2: 'لندن', isChecked: false),
  Omar(name1: 'كم عدد إخوة سيدنا يوسف عليه السلام', name2: '11 أخ', isChecked: false),
  Omar(name1: 'أين أوصى نزار القباني أن يدفن', name2: 'دمشق', isChecked: false),
  Omar(name1: 'ما هو البرج المائل في العالم', name2: 'برج بيزا', isChecked: false),
  Omar(name1: 'كم عدد اللغات الرسمية المستخدمة في الولايات المتحدة', name2: '6 لغات', isChecked: false),
  Omar(name1: 'ما المعركة التي انتصر فيها السلاجقة على جيش الروم', name2: 'ملازكرت', isChecked: false),
  Omar(name1: 'ما هي عاصمة تونس', name2: 'تونس', isChecked: false),
  Omar(name1: 'من هو الفيلسوف العربي المشهور بمقدمته', name2: 'ابن خلدون', isChecked: false),
  Omar(name1: 'في أي سورة وردت آية الكرسي', name2: 'البقرة', isChecked: false),
  Omar(name1: 'ما هي جنسية المجاهد عمر المختار', name2: 'ليبي', isChecked: false),
  Omar(name1: 'من هو أصحاب الأيكة', name2: 'قوم شعيب', isChecked: false),
  Omar(name1: 'ما هي عاصمة الجزائر', name2: 'الجزائر', isChecked: false),
  Omar(name1: 'ما العملة الرئيسية في الجزائر', name2: 'الدينار', isChecked: false),
  Omar(name1: 'من هو آخر حاكم لقب بخليفة المسلمين', name2: 'عبد المجيد الثاني', isChecked: false),
  Omar(name1: 'من هو الذي قتل حمزة بن عبد المطلب', name2: 'من هو الذي قتل حمزة بن عبد المطلب', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: 'الخرطوم', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: '', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: 'الخرطوم', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: '', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: 'الخرطوم', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: '', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: 'الخرطوم', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: '', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: 'الخرطوم', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: '', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: 'الخرطوم', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: '', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: 'الخرطوم', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: '', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: 'الخرطوم', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: '', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: 'الخرطوم', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: '', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),
  Omar(name1: 'من هو أغني رجل بالعالم', name2: 'الخرطوم', isChecked: false),
  Omar(name1: 'ما هي أقوي دوله بالعالم', name2: 'i love you7', isChecked: false),
  Omar(name1: 'كم عدد ألوان علم أمريكا', name2: 'i love you8', isChecked: false),
  Omar(name1: 'من هو أذكي طفل في العالم', name2: 'i love you9', isChecked: false),
  Omar(name1: 'كم سنة عاشها سيدنا نوح عليه السلام', name2: 'i love you10', isChecked: false),

];*/